### ISSUE TITLE
would you bump up rubygems' rack-offline version to v0.6.3 or higher?

### ISSUE THREAD

**Issue by sanemat** [wycats/rack-offline#19]
would you bump up ruby gems version?
0.6.2 August 16, 2011. After this, you adjust rails3.1 asset pipeline and 3.2.

**Comment by ptyagi16** [comment]
+1. The official rails gem is too old and will save a lot of people wasted hours figuring out why it does not work with rails 3.1.  I know I did.

**Comment by matharden** [comment]
+1. Could anyone explain how to fix this? I need this gem like yesterday!

**Comment by ptyagi16** [comment]
I worked from kristenhazard's fork for Ralis 3.1 (https://github.com/kristenhazard/rack-offline/network). Initially i used gem with git hub url. I ended up moving the gem to my lib folder for some other customizations and changes.

**Comment by ansonhoyt** [comment]
+1 @matharden Since it's just a matter or releasing a new version, you can simply reference the master branch rather than the current version:

```
gem 'rack-offline', :git => 'https://github.com/wycats/rack-offline.git'
```

**Comment by wycats** [comment]
Done.

**Comment by ansonhoyt** [comment]
Thank you sir.
