### ISSUE TITLE
undefined method `public', Rails 3.2.3 & 3.2.1

### ISSUE THREAD

**Issue by matharden** [wycats/rack-offline#21]
I've followed the instructions on the readme and the RailsCast (http://railscasts.com/episodes/247-offline-apps-part-1) on Rails on both Rails 3.2.3 and 3.2.1 but I get the same error when I request /application.manifest. What does this mean?

undefined method `public' for #Rails::Paths::Root:0x007faa726fde88

Here's the full trace

rack-offline (0.6.2) lib/rack-offline.rb:12:in `initialize'
rack-offline (0.6.2) lib/rack-offline.rb:6:in`new'
rack-offline (0.6.2) lib/rack-offline.rb:6:in `call'
journey (1.0.3) lib/journey/router.rb:68:in`block in call'
journey (1.0.3) lib/journey/router.rb:56:in `each'
journey (1.0.3) lib/journey/router.rb:56:in`call'
actionpack (3.2.3) lib/action_dispatch/routing/route_set.rb:600:in `call'
sass (3.1.19) lib/sass/plugin/rack.rb:54:in`call'
actionpack (3.2.3) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.1) lib/rack/etag.rb:23:in`call'
rack (1.4.1) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.2.3) lib/action_dispatch/middleware/head.rb:14:in`call'
actionpack (3.2.3) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.3) lib/action_dispatch/middleware/flash.rb:242:in`call'
rack (1.4.1) lib/rack/session/abstract/id.rb:205:in `context'
rack (1.4.1) lib/rack/session/abstract/id.rb:200:in`call'
actionpack (3.2.3) lib/action_dispatch/middleware/cookies.rb:338:in `call'
activerecord (3.2.3) lib/active_record/query_cache.rb:64:in`call'
activerecord (3.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:467:in `call'
actionpack (3.2.3) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
activesupport (3.2.3) lib/active_support/callbacks.rb:405:in `_run__619295624823630679__call__1725191931782040833__callbacks'
activesupport (3.2.3) lib/active_support/callbacks.rb:405:in`__run_callback'
activesupport (3.2.3) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.3) lib/active_support/callbacks.rb:81:in`run_callbacks'
actionpack (3.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.3) lib/action_dispatch/middleware/reloader.rb:65:in`call'
actionpack (3.2.3) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
actionpack (3.2.3) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.3) lib/rails/rack/logger.rb:26:in`call_app'
railties (3.2.3) lib/rails/rack/logger.rb:16:in `call'
actionpack (3.2.3) lib/action_dispatch/middleware/request_id.rb:22:in`call'
rack (1.4.1) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.1) lib/rack/runtime.rb:17:in`call'
activesupport (3.2.3) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.1) lib/rack/lock.rb:15:in`call'
actionpack (3.2.3) lib/action_dispatch/middleware/static.rb:62:in `call'
railties (3.2.3) lib/rails/engine.rb:479:in`call'
railties (3.2.3) lib/rails/application.rb:220:in `call'
rack (1.4.1) lib/rack/content_length.rb:14:in`call'
railties (3.2.3) lib/rails/rack/log_tailer.rb:14:in `call'
rack (1.4.1) lib/rack/handler/webrick.rb:59:in`service'
/Users/matharden/.rvm/rubies/ruby-1.9.2-p318/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
/Users/matharden/.rvm/rubies/ruby-1.9.2-p318/lib/ruby/1.9.1/webrick/httpserver.rb:70:in`run'
/Users/matharden/.rvm/rubies/ruby-1.9.2-p318/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'

**Comment by seabre** [comment]
Put this in your `Gemfile`:

``` ruby
gem "rack-offline", :git => "git://github.com/wycats/rack-offline.git"
```

**Comment by matharden** [comment]
Yep, that fixed it. I'll always try that in future. Thanks @seabre
