### ISSUE TITLE
caching not working with rack::offline in rails 4 

### ISSUE THREAD

**Issue by vishnurkrishnan** [wycats/rack-offline#32]
HI,
I am trying to add the offline access with my rails 4 application with the reference of railscast (http://railscasts.com/episodes/248-offline-apps-part-2), but the problem with rails 4 is its not caching the JS & CSS files. its seems like

CACHE MANIFEST
 b84e022ceae173fbc8d0c0dff68b25e9109869d744f42f1cacebfa87b96865a7
404.html
422.html
500.html

NETWORK:
*
is there any way to do the caching js & css  with rails 4

**Comment by benmwendwa** [comment]
I am facing the same problem too. Did you find a way to solve this?
