### ISSUE TITLE
undefined method 'public'

### ISSUE THREAD

**Issue by abelta** [wycats/rack-offline#4]
The manifest isn't working for me so I visited the address it's supposed to live in: "/application.manifest" and this is the error I got:

undefined method `public' for #Rails::Paths::Root:0xb6401b0c

with the following env dump:

GATEWAY_INTERFACE: "CGI/1.1"
HTTP_ACCEPT: "application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,_/_;q=0.5"
HTTP_ACCEPT_CHARSET: "ISO-8859-1,utf-8;q=0.7,*;q=0.3"
HTTP_ACCEPT_ENCODING: "gzip,deflate,sdch"
HTTP_ACCEPT_LANGUAGE: "en-US,en;q=0.8"
HTTP_CACHE_CONTROL: "max-age=0"
HTTP_CONNECTION: "keep-alive"
HTTP_COOKIE: "__utmz=162457789.1273070594.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); user_credentials=9aa5ff19695022d44a1981317cf97e9fd2a2f2dcb145f4dfcc17853aa36474526affec0e2f38364628bc68998ac568bbf54d18ff2e604e43e873154d0a34c46b%3A%3A926; __utma=162457789.513641191.1284324662.1284804676.1284837523.21; __utmc=162457789; __utmb=162457789.1.10.1284837523; _got3ds_session=BAh7ByIQX2NzcmZfdG9rZW4iMXVYNEt2NThKSXV3N3JFaVd6TEs0MTk0T0owU1piKzIrbXBmaGZ2Tkp6eXM9Ig9zZXNzaW9uX2lkIiVkNDJhNTBiYzkzYjlkMTVjYzg3MWQ0YTJjMDMzNjc4YQ%3D%3D--68fc5c92db116b73d28f764e02de416542922649"
HTTP_HOST: "0.0.0.0:3000"
HTTP_USER_AGENT: "Mozilla/5.0 (X11; U; Linux i686; en-US) AppleWebKit/534.7 (KHTML, like Gecko) Chrome/7.0.517.8 Safari/534.7"
HTTP_VERSION: "HTTP/1.1"
PATH_INFO: "/application.manifest"
QUERY_STRING: ""
REMOTE_ADDR: "127.0.0.1"
REMOTE_HOST: "localhost"
REQUEST_METHOD: "GET"
REQUEST_PATH: "/"
REQUEST_URI: "http://0.0.0.0:3000/application.manifest"
SCRIPT_NAME: ""
SERVER_NAME: "0.0.0.0"
SERVER_PORT: "3000"
SERVER_PROTOCOL: "HTTP/1.1"
SERVER_SOFTWARE: "WEBrick/1.3.1 (Ruby/1.8.7/2010-06-23)"
action_dispatch.parameter_filter: [:password]
action_dispatch.request.content_type: nil
action_dispatch.request.parameters: {}
action_dispatch.request.path_parameters: {}
action_dispatch.request.query_parameters: {}
action_dispatch.request.request_parameters: {}
rack.errors: #IO:0xb7595558
rack.input: #StringIO:0xb64961d0
rack.multiprocess: false
rack.multithread: false
rack.request.cookie_hash: {"user_credentials"=>"9aa5ff19695022d44a1981317cf97e9fd2a2f2dcb145f4dfcc17853aa36474526affec0e2f38364628bc68998ac568bbf54d18ff2e604e43e873154d0a34c46b::926", "__utma"=>"162457789.513641191.1284324662.1284804676.1284837523.21", "__utmb"=>"162457789.1.10.1284837523", "__utmc"=>"162457789", "_got3ds_session"=>"BAh7ByIQX2NzcmZfdG9rZW4iMXVYNEt2NThKSXV3N3JFaVd6TEs0MTk0T0owU1piKzIrbXBmaGZ2Tkp6eXM9Ig9zZXNzaW9uX2lkIiVkNDJhNTBiYzkzYjlkMTVjYzg3MWQ0YTJjMDMzNjc4YQ==--68fc5c92db116b73d28f764e02de416542922649", "__utmz"=>"162457789.1273070594.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)"}
rack.request.cookie_string: "__utmz=162457789.1273070594.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); user_credentials=9aa5ff19695022d44a1981317cf97e9fd2a2f2dcb145f4dfcc17853aa36474526affec0e2f38364628bc68998ac568bbf54d18ff2e604e43e873154d0a34c46b%3A%3A926; __utma=162457789.513641191.1284324662.1284804676.1284837523.21; __utmc=162457789; __utmb=162457789.1.10.1284837523; _got3ds_session=BAh7ByIQX2NzcmZfdG9rZW4iMXVYNEt2NThKSXV3N3JFaVd6TEs0MTk0T0owU1piKzIrbXBmaGZ2Tkp6eXM9Ig9zZXNzaW9uX2lkIiVkNDJhNTBiYzkzYjlkMTVjYzg3MWQ0YTJjMDMzNjc4YQ%3D%3D--68fc5c92db116b73d28f764e02de416542922649"
rack.request.query_hash: {}
rack.request.query_string: ""
rack.run_once: false
rack.session: {"_csrf_token"=>"uX4Kv58JIuw7rEiWzLK4194OJ0SZb+2+mpfhfvNJzys=", "session_id"=>"d42a50bc93b9d15cc871d4a2c033678a"}
rack.session.options: {:httponly=>true, :expire_after=>nil, :id=>"d42a50bc93b9d15cc871d4a2c033678a", :path=>"/", :key=>"_session_id", :domain=>nil}
rack.url_scheme: "http"
rack.version: [1, 1]

I don't understand a word of it but I guess it's parsing the "public" folder as a method?

**Comment by danielmorrison** [comment]
Yeah, I'm getting that too. It looks like something changed with Rails::Paths. I'm not familiar enough yet to figure out the best way forward, but I'll look.

**Comment by davidsulc** [comment]
I ran into the same issue, and submitted a pull request ( https://github.com/wycats/rack-offline/pull/17 ).

Please let me know if that pull request addresses your issue also.

**Comment by davidsulc** [comment]
Also, check out this pull request https://github.com/wycats/rack-offline/pull/16

It seems to also correct the issue.

**Comment by wycats** [comment]
Done and done.
